import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
import Direksyon from './components/direksyon'
import View from './view'

export default function Home() {
  return (
    <>
      <Head>
        <title>DEVLOOP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Direksyon/>
      </main>
    </>
  )
}
