import styles from '@/styles/Home.module.css'
import Sidebar from './components/sidebar'
import Head from 'next/head'
import Gwoup from './components/gwoup'
import Direksyon from './components/direksyon'
import Wol from './components/wol'
import { useState } from 'react'


export default function View(children:any){

    const [viewTitle,setviewTitle]=useState("")

    const handleView=(data:any)=>{
        setviewTitle(data)
        alert(viewTitle)
        {
            <View>
                
            </View>
        }
    }
  
    return(
        
        <>
            <Head>
                <title>DEVLOOP</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <div className={styles.sidebar}>
            <h1>Devloop</h1>
            <div className={styles.coverNav}>
                {/* <Link className={styles.Link} href={{pathname:"/view",query:{title:"Direksyon"}}} >Direksyon</Link>
                <Link className={styles.Link} href={{pathname:"/view",query:{title:"Gwoup"}}}>gwoup</Link>
                <Link className={styles.Link} href={{pathname:"/view",query:{title:"Wol"}}}>Wòl</Link> */}
                <ul>
                    <li onClick={()=>{handleView("Direksyon")}}>Direksyon</li>
                    <li onClick={()=>{handleView("Gwoup")}}>Gwoup</li>
                    <li>Wol</li>
                </ul>
            </div>

        </div>
        <View>
            {children}
        </View>
            
        </>   
    )
}